first commit
dsivanov5372/java-shareit pull request #1
Opened 2023-01-15 17:09 UTC by dsivanov5372

2023-01-15 18:09 UTC, EvgenyKoptubenko commented
@github-actions
ShareIt API Tests / build / build-shareit (pull_request) Failing after 54s
Падает проверка

2023-01-15 18:11 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
попробуй объединить обработчики разных эксепшенов, написав их через запятую
https://www.baeldung.com/exception-handling-for-rest-with-spring

2023-01-15 18:16 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Всего одно предложение по улучшению

2023-01-16 19:25 UTC, dsivanov5372 commented
> @github-actions
> ShareIt API Tests / build / build-shareit (pull_request) Failing after 54s
> Падает проверка

Скорее всего проверка может искать тесты для ветки с определённым названием, про что ничего не было сказано в тз, поэтому падает билд, но неработающую программу я бы явно не отправлял на проверку)

2023-01-16 19:39 UTC, merged