add items request and unit and integration tests
dsivanov5372/java-shareit pull request #4
Opened 2023-02-01 15:39 UTC by dsivanov5372

2023-02-01 20:06 UTC, EvgenyKoptubenko commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        Booking booking = Booking.builder()
Создание booking повторяется во всех методах. Попробуй вынести его

2023-02-01 20:08 UTC, EvgenyKoptubenko commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    public void setUp() {
модификатор public в тестах не нужен

2023-02-01 20:10 UTC, EvgenyKoptubenko commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +        assertEquals(ex.getMessage(), "Item is not available!");
В assertEquals сперва идет expected value, а потом actual value. Желательно поменять местами параметры, чтобы было красиво

2023-02-01 20:13 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/paginator/Paginator.java
> +public class Paginator {
Попробуй переписать на Pageable https://www.baeldung.com/spring-data-jpa-pagination-sorting

2023-02-01 20:16 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      }
На 93-й строке странный код. Ищется пользователь по идентификатору, но подставляется идентификатор комментария

2023-02-01 20:20 UTC, EvgenyKoptubenko commented
Есть замечание по предыдущей итерации. Если создать пользователя, а потом попробовать изменить его, то дает задать ему неверный email
{
	"id": 1,
	"name": "nameItem",
	"email": "wrong_emailmail.com"
}

2023-02-01 20:21 UTC, EvgenyKoptubenko commented
Если обновлять пользователя без изменений email, то пишет, что такой email address is used. Т.е. нельзя изменить поля

2023-02-01 20:23 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item addItem(@RequestBody ItemDto item,
На запрос
curl --request POST \
  --url http://localhost:8080/items \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameItem",
	"description":"descriptionItem",
	"available":true
}'

Приходит ошибка
{
	"error": "could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
}

2023-02-01 20:23 UTC, EvgenyKoptubenko requested changes
Есть несколько замечаний. Поправь, пожалуйста.

2023-02-02 17:01 UTC, dsivanov5372 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item addItem(@RequestBody ItemDto item,
Создал юзера с айди 1, затем отправил такой же запрос

2023-02-02 17:01 UTC, dsivanov5372 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item addItem(@RequestBody ItemDto item,
вот что получил:`{
	"id": 1,
	"name": "nameItem",
	"description": "descriptionItem",
	"available": true,
	"owner": 1,
	"requestId": null,
	"lastBooking": null,
	"nextBooking": null,
	"comments": null
}`

2023-02-02 19:27 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-02-04 13:36 UTC, merged